name: fetchSubs1

on:
  push:
    branches: main
  workflow_dispatch:
  schedule:
   - cron: '20 */8 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: 设置 Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        python -m pip install urllib3 requests PyYAML
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 执行任务
      run: |
        python ./utils/chf.py
    - name: 检查变更
      id: git-status
      run: |
        git status --porcelain
    - name: 提交更改
      
      run: |                 
        git config --local user.email "1024304930@qq.com"
        git config --local user.name "zyj68"
        git add subs/*
        git commit -m "更新订阅链接"
    - name: 推送更改
      if: ${{ steps.git-status.outputs.stdout != '' }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        branch: main
